version: '2'

services:
  agents-app:
    image: agents-app
    environment:
      APP_PORT: "30001"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "30001:30001"
    restart: unless-stopped
