# assitent
assistant_task:
  description: >
    Respond to the user's message: {user_message}. Use the provided conversation history {context}",
  expected_output: >
    Your output should be a relevant, accurate, and engaging response that directly addresses the user's 
    query or continues the conversation logically.

search_product_task:
  description: >
    Retrieve detailed information about a product by its SKU.
  expected_output: >
    Full product details or an error message.
  agent: manager
  tools: [MagentoTool.search_product]

create_product_task:
  description: >
    Add a new product to Magento with the given name, price, and description.
  expected_output: >
    Confirmation of product creation or error details.
  agent: manager
  tools: [MagentoTool.create_product]

update_stock_task:
  description: >
    Update the stock quantity of a product in Magento.
  expected_output: >
    Confirmation of stock update or error details.
  agent: manager
  tools: [MagentoTool.update_stock]

list_orders_task:
  description: >
    Retrieve the most recent orders from Magento.
  expected_output: >
    A list of orders with their IDs and statuses.
  agent: manager
  tools: [MagentoTool.list_orders]


# Product creation stuff
research_product_market:
  description: >
    Conduct thorough research online to identify competitor products, their pricing, descriptions, and key features about {topic}. 
    Ensure the data is relevant and up-to-date.
  expected_output: >
    A list containing:
    - Competitor product names
    - Prices
    - Key features
    - Common attributes
  #agent: internet_researcher

define_average_price:
  description: >
    Analyze the pricing data collected by the internet_researcher and define an optimal average price for the {topic} product.
  expected_output: >
    - Recommended average price in float format
  #agent: pricing_analyst

generate_product_images:
  description: >
    Create visually appealing images for the {topic} product listing. Include high-resolution images, variations (e.g., colors, angles), and a hero image.
  expected_output: >
    A set of images in the following format:
    - Main hero image
    - Product variations (size, color, angle views)
  #agent: image_creator

publish_to_adobe_commerce:
  description: >
    Publish the validated product data, including all details and images, to Adobe Commerce using its API.
  expected_output: >
    A confirmation message that the product has been successfully published.
  #agent: publisher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  #agent: reporting_analyst

research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  #agent: researcher

# validate_final_product:
#   description: >
#     Review the final product data, including name, description, pricing, attributes, and images. 
#     Ensure all details meet quality and platform standards.
#   expected_output: >
#     A list of any corrections needed or confirmation that the product is ready for publishing.
#   agent: data_validator
